version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongPass123!
      - MSSQL_DB=DriversDB
    ports:
      - "1433:1433"  # Maps SQL Server's port 1433 to the host
    networks:
      - app-network

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=YourDatabaseName;User Id=sa;Password=YourPassword123;
    ports:
      - "5000:80"  # Maps the container's port 80 to the host's port 5000
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
